"""Initial migration.

Revision ID: 958b9a6bc669
Revises: 
Create Date: 2020-07-25 16:05:36.271955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '958b9a6bc669'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('note_id', sa.String(length=48), nullable=False),
    sa.Column('paper_id', sa.String(length=48), nullable=True),
    sa.Column('project_id', sa.String(length=48), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('note_id')
    )
    op.create_table('papers',
    sa.Column('paper_id', sa.String(length=48), nullable=False),
    sa.Column('pid', sa.String(length=64), nullable=True),
    sa.Column('pid_type', sa.String(length=8), nullable=True),
    sa.Column('project_id', sa.String(length=48), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('pub_date', sa.String(length=32), nullable=True),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('journal', sa.String(length=128), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('ss_st', sa.String(length=8), nullable=True),
    sa.Column('ss_pr', sa.String(length=8), nullable=True),
    sa.Column('ss_rs', sa.String(length=8), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('paper_id')
    )
    op.create_table('projects',
    sa.Column('project_id', sa.String(length=48), nullable=False),
    sa.Column('keystr', sa.String(length=64), nullable=True),
    sa.Column('owner_uid', sa.String(length=64), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('is_deleted', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('project_id'),
    sa.UniqueConstraint('keystr')
    )
    op.create_table('users',
    sa.Column('uid', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('first_name', sa.String(length=45), nullable=True),
    sa.Column('last_name', sa.String(length=45), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=True),
    sa.Column('is_deleted', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('rel_project_users',
    sa.Column('project_id', sa.String(length=48), nullable=False),
    sa.Column('uid', sa.String(length=48), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.ForeignKeyConstraint(['uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('project_id', 'uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rel_project_users')
    op.drop_table('users')
    op.drop_table('projects')
    op.drop_table('papers')
    op.drop_table('notes')
    # ### end Alembic commands ###
