"""empty message

Revision ID: fb3fb8587265
Revises: 958b9a6bc669
Create Date: 2020-10-21 21:38:14.564807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb3fb8587265'
down_revision = '958b9a6bc669'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('ss_ex', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papers', 'ss_ex')
    # ### end Alembic commands ###
